/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees.that.reminisce;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class DriverTest {
    @Test public void appHasAGreeting() {
        Driver classUnderTest = new Driver();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
